# Docker Secrets を使用した本番環境用設定
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up

services:
  news-processor:
    environment:
      # 環境変数からシークレットファイルを参照
      - CLAUDE_API_KEY_FILE=/run/secrets/claude_api_key
    secrets:
      - claude_api_key
    
  frontend-prod:
    secrets:
      - claude_api_key

secrets:
  # Claude API キーのシークレット設定
  claude_api_key:
    file: ./secrets/claude_api_key.txt
    
  # 将来の拡張用シークレット
  database_password:
    external: true
    name: ai_news_db_password
    
  ssl_certificate:
    external: true
    name: ai_news_ssl_cert